### ISSUE TITLE
Where to submit solution?

### ISSUE THREAD

**Issue by kkapelon** [ProlificLabs/shakesearch#7]
It is not clear from the readme what do I need to do once I have my solution (i.e. my forked repo).

Do I contact a specific email? Do I submit a form somewhere? Basically who do I send my solution to?

**Comment by DanielGattiMP** [comment]
Hi, I don't work in Pulley but based on this  [job post](https://www.golangprojects.com/golang-go-job-edr-Remote-Golang-Engineer-San-Francisco-Pulley-remotework.html) you should send it to `careers@pulley dot com`
